Importo 
request: para las llamadas a la API
pandas: para transformar y analizar los datos
dotenv y os: Para leer la API key desde el archivo .env, sin exponerla en el código

In [16]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os

Cargo el archivo .env para leer la API key

In [17]:
load_dotenv()
NASA_API_KEY = os.getenv("NASA_API_KEY")

Verifico que la conexion con la API esté funcionando correctamente

In [18]:
url = "https://api.nasa.gov/neo/rest/v1/feed"

params = {
    "start_date": "2024-01-01",
    "end_date": "2024-01-07",
    "api_key": NASA_API_KEY
}

response = requests.get(url, params=params)

print(response.status_code)

200

In [19]:
data = response.json()
print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['links', 'element_count', 'near_earth_objects'])

In [6]:
neos = data["near_earth_objects"]
print(type(neos))
print(neos.keys())

<class 'dict'>
dict_keys(['2024-01-02', '2024-01-01', '2024-01-04', '2024-01-03', '2024-01-06', '2024-01-05', '2024-01-07'])

In [7]:
primer_dia = neos["2024-01-01"]
print(type(primer_dia))
print(len(primer_dia))
print(primer_dia[0])

<class 'list'>
3
{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3724393?api_key=QTiPpbhjU5Acq8of527QVIM7XQ8teOgd1hUEZcO5'}, 'id': '3724393', 'neo_reference_id': '3724393', 'name': '(2015 OD22)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3724393', 'absolute_magnitude_h': 21.21, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.152249185, 'estimated_diameter_max': 0.3404395273}, 'meters': {'estimated_diameter_min': 152.249185036, 'estimated_diameter_max': 340.4395272595}, 'miles': {'estimated_diameter_min': 0.0946032284, 'estimated_diameter_max': 0.2115392495}, 'feet': {'estimated_diameter_min': 499.5052162336, 'estimated_diameter_max': 1116.9276186141}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-01', 'close_approach_date_full': '2024-Jan-01 11:58', 'epoch_date_close_approach': 1704110280000, 'relative_velocity': {'kilometers_per_second': '25.3931645932', 'kilometers_per_hour': '91415.3925356518', 'miles_per_hour': '56801.969878611'}, 'miss_distance': {'astronomical': '0.4372881787', 'lunar': '170.1051015143', 'kilometers': '65417380.109699369', 'miles': '40648475.1053305322'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}

In [8]:
asteroids = []

for date, neo_list in neos.items():
    for neo in neo_list:
        asteroid = {
            "id": neo["id"],
            "name": neo["name"],
            "is_potentially_hazardous": neo["is_potentially_hazardous_asteroid"],
            "diameter_km_min": neo["estimated_diameter"]["kilometers"]["estimated_diameter_min"],
            "diameter_km_max": neo["estimated_diameter"]["kilometers"]["estimated_diameter_max"],
            "close_approach_date": neo["close_approach_data"][0]["close_approach_date"],
            "miss_distance_km": neo["close_approach_data"][0]["miss_distance"]["kilometers"],
            "velocity_kmh": neo["close_approach_data"][0]["relative_velocity"]["kilometers_per_hour"]
        }
        asteroids.append(asteroid)

print(len(asteroids))

45

In [9]:
df = pd.DataFrame(asteroids)
df.head()

,id,name,is_potentially_hazardous,diameter_km_min,diameter_km_max,close_approach_date,miss_distance_km,velocity_kmh
0,2415949,415949 (2001 XY10),False,0.355267,0.794401,2024-01-02,50452409.349026638,57205.8951204341
1,3160747,(2003 SR84),False,0.016771,0.037501,2024-01-02,19798169.933318188,38589.054833182
2,3309828,(2005 YQ96),True,0.199781,0.446725,2024-01-02,24984732.559194501,56413.0143519451
3,3457842,(2009 HC21),False,0.101054,0.225964,2024-01-02,73609796.924990823,21891.1182185894
4,3553062,(2010 XA11),False,0.016016,0.035813,2024-01-02,35275514.131770482,31468.9783588978

In [10]:
print(df.shape)
print(df["is_potentially_hazardous"].value_counts())

(45, 8)
is_potentially_hazardous
False    39
True      6
Name: count, dtype: int64

In [11]:
print(df.dtypes)
print(df.isnull().sum())

id                              str
name                            str
is_potentially_hazardous       bool
diameter_km_min             float64
diameter_km_max             float64
close_approach_date             str
miss_distance_km                str
velocity_kmh                    str
dtype: object
id                          0
name                        0
is_potentially_hazardous    0
diameter_km_min             0
diameter_km_max             0
close_approach_date         0
miss_distance_km            0
velocity_kmh                0
dtype: int64

In [12]:
df["miss_distance_km"] = pd.to_numeric(df["miss_distance_km"])
df["velocity_kmh"] = pd.to_numeric(df["velocity_kmh"])
df["close_approach_date"] = pd.to_datetime(df["close_approach_date"])

print(df.dtypes)

id                                     str
name                                   str
is_potentially_hazardous              bool
diameter_km_min                    float64
diameter_km_max                    float64
close_approach_date         datetime64[us]
miss_distance_km                   float64
velocity_kmh                       float64
dtype: object

In [13]:
import time
from datetime import datetime, timedelta

def fetch_neos(start_date, end_date, api_key):
    url = "https://api.nasa.gov/neo/rest/v1/feed"
    params = {
        "start_date": start_date,
        "end_date": end_date,
        "api_key": api_key
    }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        return response.json()["near_earth_objects"]
    else:
        print(f"Error {response.status_code} para {start_date}")
        return {}

In [14]:
start = datetime(1995, 1, 1)
end = datetime(2025, 1, 1)

all_asteroids = []
current = start

while current < end:
    week_end = current + timedelta(days=7)
    print(f"Bajando: {current.date()} a {week_end.date()}")
    current = week_end

Bajando: 1995-01-01 a 1995-01-08
Bajando: 1995-01-08 a 1995-01-15
Bajando: 1995-01-15 a 1995-01-22
Bajando: 1995-01-22 a 1995-01-29
Bajando: 1995-01-29 a 1995-02-05
Bajando: 1995-02-05 a 1995-02-12
Bajando: 1995-02-12 a 1995-02-19
Bajando: 1995-02-19 a 1995-02-26
Bajando: 1995-02-26 a 1995-03-05
Bajando: 1995-03-05 a 1995-03-12
Bajando: 1995-03-12 a 1995-03-19
Bajando: 1995-03-19 a 1995-03-26
Bajando: 1995-03-26 a 1995-04-02
Bajando: 1995-04-02 a 1995-04-09
Bajando: 1995-04-09 a 1995-04-16
Bajando: 1995-04-16 a 1995-04-23
Bajando: 1995-04-23 a 1995-04-30
Bajando: 1995-04-30 a 1995-05-07
Bajando: 1995-05-07 a 1995-05-14
Bajando: 1995-05-14 a 1995-05-21
Bajando: 1995-05-21 a 1995-05-28
Bajando: 1995-05-28 a 1995-06-04
Bajando: 1995-06-04 a 1995-06-11
Bajando: 1995-06-11 a 1995-06-18
Bajando: 1995-06-18 a 1995-06-25
Bajando: 1995-06-25 a 1995-07-02
Bajando: 1995-07-02 a 1995-07-09
Bajando: 1995-07-09 a 1995-07-16
Bajando: 1995-07-16 a 1995-07-23
Bajando: 1995-07-23 a 1995-07-30
Bajando: 1995-07-30 a 1995-08-06
Bajando: 1995-08-06 a 1995-08-13
Bajando: 1995-08-13 a 1995-08-20
Bajando: 1995-08-20 a 1995-08-27
Bajando: 1995-08-27 a 1995-09-03
Bajando: 1995-09-03 a 1995-09-10
Bajando: 1995-09-10 a 1995-09-17
Bajando: 1995-09-17 a 1995-09-24
Bajando: 1995-09-24 a 1995-10-01
Bajando: 1995-10-01 a 1995-10-08
Bajando: 1995-10-08 a 1995-10-15
Bajando: 1995-10-15 a 1995-10-22
Bajando: 1995-10-22 a 1995-10-29
Bajando: 1995-10-29 a 1995-11-05
Bajando: 1995-11-05 a 1995-11-12
Bajando: 1995-11-12 a 1995-11-19
Bajando: 1995-11-19 a 1995-11-26
Bajando: 1995-11-26 a 1995-12-03
Bajando: 1995-12-03 a 1995-12-10
Bajando: 1995-12-10 a 1995-12-17
Bajando: 1995-12-17 a 1995-12-24
Bajando: 1995-12-24 a 1995-12-31
Bajando: 1995-12-31 a 1996-01-07
Bajando: 1996-01-07 a 1996-01-14
Bajando: 1996-01-14 a 1996-01-21
Bajando: 1996-01-21 a 1996-01-28
Bajando: 1996-01-28 a 1996-02-04
Bajando: 1996-02-04 a 1996-02-11
Bajando: 1996-02-11 a 1996-02-18
Bajando: 1996-02-18 a 1996-02-25
Bajando: 1996-02-25 a 1996-03-03
Bajando: 1996-03-03 a 1996-03-10
Bajando: 1996-03-10 a 1996-03-17
Bajando: 1996-03-17 a 1996-03-24
Bajando: 1996-03-24 a 1996-03-31
Bajando: 1996-03-31 a 1996-04-07
Bajando: 1996-04-07 a 1996-04-14
Bajando: 1996-04-14 a 1996-04-21
Bajando: 1996-04-21 a 1996-04-28
Bajando: 1996-04-28 a 1996-05-05
Bajando: 1996-05-05 a 1996-05-12
Bajando: 1996-05-12 a 1996-05-19
Bajando: 1996-05-19 a 1996-05-26
Bajando: 1996-05-26 a 1996-06-02
Bajando: 1996-06-02 a 1996-06-09
Bajando: 1996-06-09 a 1996-06-16
Bajando: 1996-06-16 a 1996-06-23
Bajando: 1996-06-23 a 1996-06-30
Bajando: 1996-06-30 a 1996-07-07
Bajando: 1996-07-07 a 1996-07-14
Bajando: 1996-07-14 a 1996-07-21
Bajando: 1996-07-21 a 1996-07-28
Bajando: 1996-07-28 a 1996-08-04
Bajando: 1996-08-04 a 1996-08-11
Bajando: 1996-08-11 a 1996-08-18
Bajando: 1996-08-18 a 1996-08-25
Bajando: 1996-08-25 a 1996-09-01
Bajando: 1996-09-01 a 1996-09-08
Bajando: 1996-09-08 a 1996-09-15
Bajando: 1996-09-15 a 1996-09-22
Bajando: 1996-09-22 a 1996-09-29
Bajando: 1996-09-29 a 1996-10-06
Bajando: 1996-10-06 a 1996-10-13
Bajando: 1996-10-13 a 1996-10-20
Bajando: 1996-10-20 a 1996-10-27
Bajando: 1996-10-27 a 1996-11-03
Bajando: 1996-11-03 a 1996-11-10
Bajando: 1996-11-10 a 1996-11-17
Bajando: 1996-11-17 a 1996-11-24
Bajando: 1996-11-24 a 1996-12-01
Bajando: 1996-12-01 a 1996-12-08
Bajando: 1996-12-08 a 1996-12-15
Bajando: 1996-12-15 a 1996-12-22
Bajando: 1996-12-22 a 1996-12-29
Bajando: 1996-12-29 a 1997-01-05
Bajando: 1997-01-05 a 1997-01-12
Bajando: 1997-01-12 a 1997-01-19
Bajando: 1997-01-19 a 1997-01-26
Bajando: 1997-01-26 a 1997-02-02
Bajando: 1997-02-02 a 1997-02-09
Bajando: 1997-02-09 a 1997-02-16
Bajando: 1997-02-16 a 1997-02-23
Bajando: 1997-02-23 a 1997-03-02
Bajando: 1997-03-02 a 1997-03-09
Bajando: 1997-03-09 a 1997-03-16
Bajando: 1997-03-16 a 1997-03-23
Bajando: 1997-03-23 a 1997-03-30
Bajando: 1997-03-30 a 1997-04-06
Bajando: 1997-04-06 a 1997-04-13
Bajando: 1997-04-13 a 1997-04-20
Bajando: 1997-04-20 a 1997-04-27
Bajando: 1997-04-27 a 1997-05-04
Bajando: 1997-05-04 a 1997-05-11
Bajando: 1997-05-11 a 1997-05-18
Bajando: 1997-05-18 a 1997-05-25
Bajando: 1997-05-25 a 1997-06-01
Bajando: 1997-06-01 a 1997-06-08
Bajando: 1997-06-08 a 1997-06-15
Bajando: 1997-06-15 a 1997-06-22
Bajando: 1997-06-22 a 1997-06-29
Bajando: 1997-06-29 a 1997-07-06
Bajando: 1997-07-06 a 1997-07-13
Bajando: 1997-07-13 a 1997-07-20
Bajando: 1997-07-20 a 1997-07-27
Bajando: 1997-07-27 a 1997-08-03
Bajando: 1997-08-03 a 1997-08-10
Bajando: 1997-08-10 a 1997-08-17
Bajando: 1997-08-17 a 1997-08-24
Bajando: 1997-08-24 a 1997-08-31
Bajando: 1997-08-31 a 1997-09-07
Bajando: 1997-09-07 a 1997-09-14
Bajando: 1997-09-14 a 1997-09-21
Bajando: 1997-09-21 a 1997-09-28
Bajando: 1997-09-28 a 1997-10-05
Bajando: 1997-10-05 a 1997-10-12
Bajando: 1997-10-12 a 1997-10-19
Bajando: 1997-10-19 a 1997-10-26
Bajando: 1997-10-26 a 1997-11-02
Bajando: 1997-11-02 a 1997-11-09
Bajando: 1997-11-09 a 1997-11-16
Bajando: 1997-11-16 a 1997-11-23
Bajando: 1997-11-23 a 1997-11-30
Bajando: 1997-11-30 a 1997-12-07
Bajando: 1997-12-07 a 1997-12-14
Bajando: 1997-12-14 a 1997-12-21
Bajando: 1997-12-21 a 1997-12-28
Bajando: 1997-12-28 a 1998-01-04
Bajando: 1998-01-04 a 1998-01-11
Bajando: 1998-01-11 a 1998-01-18
Bajando: 1998-01-18 a 1998-01-25
Bajando: 1998-01-25 a 1998-02-01
Bajando: 1998-02-01 a 1998-02-08
Bajando: 1998-02-08 a 1998-02-15
Bajando: 1998-02-15 a 1998-02-22
Bajando: 1998-02-22 a 1998-03-01
Bajando: 1998-03-01 a 1998-03-08
Bajando: 1998-03-08 a 1998-03-15
Bajando: 1998-03-15 a 1998-03-22
Bajando: 1998-03-22 a 1998-03-29
Bajando: 1998-03-29 a 1998-04-05
Bajando: 1998-04-05 a 1998-04-12
Bajando: 1998-04-12 a 1998-04-19
Bajando: 1998-04-19 a 1998-04-26
Bajando: 1998-04-26 a 1998-05-03
Bajando: 1998-05-03 a 1998-05-10
Bajando: 1998-05-10 a 1998-05-17
Bajando: 1998-05-17 a 1998-05-24
Bajando: 1998-05-24 a 1998-05-31
Bajando: 1998-05-31 a 1998-06-07
Bajando: 1998-06-07 a 1998-06-14
Bajando: 1998-06-14 a 1998-06-21
Bajando: 1998-06-21 a 1998-06-28
Bajando: 1998-06-28 a 1998-07-05
Bajando: 1998-07-05 a 1998-07-12
Bajando: 1998-07-12 a 1998-07-19
Bajando: 1998-07-19 a 1998-07-26
Bajando: 1998-07-26 a 1998-08-02
Bajando: 1998-08-02 a 1998-08-09
Bajando: 1998-08-09 a 1998-08-16
Bajando: 1998-08-16 a 1998-08-23
Bajando: 1998-08-23 a 1998-08-30
Bajando: 1998-08-30 a 1998-09-06
Bajando: 1998-09-06 a 1998-09-13
Bajando: 1998-09-13 a 1998-09-20
Bajando: 1998-09-20 a 1998-09-27
Bajando: 1998-09-27 a 1998-10-04
Bajando: 1998-10-04 a 1998-10-11
Bajando: 1998-10-11 a 1998-10-18
Bajando: 1998-10-18 a 1998-10-25
Bajando: 1998-10-25 a 1998-11-01
Bajando: 1998-11-01 a 1998-11-08
Bajando: 1998-11-08 a 1998-11-15
Bajando: 1998-11-15 a 1998-11-22
Bajando: 1998-11-22 a 1998-11-29
Bajando: 1998-11-29 a 1998-12-06
Bajando: 1998-12-06 a 1998-12-13
Bajando: 1998-12-13 a 1998-12-20
Bajando: 1998-12-20 a 1998-12-27
Bajando: 1998-12-27 a 1999-01-03
Bajando: 1999-01-03 a 1999-01-10
Bajando: 1999-01-10 a 1999-01-17
Bajando: 1999-01-17 a 1999-01-24
Bajando: 1999-01-24 a 1999-01-31
Bajando: 1999-01-31 a 1999-02-07
Bajando: 1999-02-07 a 1999-02-14
Bajando: 1999-02-14 a 1999-02-21
Bajando: 1999-02-21 a 1999-02-28
Bajando: 1999-02-28 a 1999-03-07
Bajando: 1999-03-07 a 1999-03-14
Bajando: 1999-03-14 a 1999-03-21
Bajando: 1999-03-21 a 1999-03-28
Bajando: 1999-03-28 a 1999-04-04
Bajando: 1999-04-04 a 1999-04-11
Bajando: 1999-04-11 a 1999-04-18
Bajando: 1999-04-18 a 1999-04-25
Bajando: 1999-04-25 a 1999-05-02
Bajando: 1999-05-02 a 1999-05-09
Bajando: 1999-05-09 a 1999-05-16
Bajando: 1999-05-16 a 1999-05-23
Bajando: 1999-05-23 a 1999-05-30
Bajando: 1999-05-30 a 1999-06-06
Bajando: 1999-06-06 a 1999-06-13
Bajando: 1999-06-13 a 1999-06-20
Bajando: 1999-06-20 a 1999-06-27
Bajando: 1999-06-27 a 1999-07-04
Bajando: 1999-07-04 a 1999-07-11
Bajando: 1999-07-11 a 1999-07-18
Bajando: 1999-07-18 a 1999-07-25
Bajando: 1999-07-25 a 1999-08-01
Bajando: 1999-08-01 a 1999-08-08
Bajando: 1999-08-08 a 1999-08-15
Bajando: 1999-08-15 a 1999-08-22
Bajando: 1999-08-22 a 1999-08-29
Bajando: 1999-08-29 a 1999-09-05
Bajando: 1999-09-05 a 1999-09-12
Bajando: 1999-09-12 a 1999-09-19
Bajando: 1999-09-19 a 1999-09-26
Bajando: 1999-09-26 a 1999-10-03
Bajando: 1999-10-03 a 1999-10-10
Bajando: 1999-10-10 a 1999-10-17
Bajando: 1999-10-17 a 1999-10-24
Bajando: 1999-10-24 a 1999-10-31
Bajando: 1999-10-31 a 1999-11-07
Bajando: 1999-11-07 a 1999-11-14
Bajando: 1999-11-14 a 1999-11-21
Bajando: 1999-11-21 a 1999-11-28
Bajando: 1999-11-28 a 1999-12-05
Bajando: 1999-12-05 a 1999-12-12
Bajando: 1999-12-12 a 1999-12-19
Bajando: 1999-12-19 a 1999-12-26
Bajando: 1999-12-26 a 2000-01-02
Bajando: 2000-01-02 a 2000-01-09
Bajando: 2000-01-09 a 2000-01-16
Bajando: 2000-01-16 a 2000-01-23
Bajando: 2000-01-23 a 2000-01-30
Bajando: 2000-01-30 a 2000-02-06
Bajando: 2000-02-06 a 2000-02-13
Bajando: 2000-02-13 a 2000-02-20
Bajando: 2000-02-20 a 2000-02-27
Bajando: 2000-02-27 a 2000-03-05
Bajando: 2000-03-05 a 2000-03-12
Bajando: 2000-03-12 a 2000-03-19
Bajando: 2000-03-19 a 2000-03-26
Bajando: 2000-03-26 a 2000-04-02
Bajando: 2000-04-02 a 2000-04-09
Bajando: 2000-04-09 a 2000-04-16
Bajando: 2000-04-16 a 2000-04-23
Bajando: 2000-04-23 a 2000-04-30
Bajando: 2000-04-30 a 2000-05-07
Bajando: 2000-05-07 a 2000-05-14
Bajando: 2000-05-14 a 2000-05-21
Bajando: 2000-05-21 a 2000-05-28
Bajando: 2000-05-28 a 2000-06-04
Bajando: 2000-06-04 a 2000-06-11
Bajando: 2000-06-11 a 2000-06-18
Bajando: 2000-06-18 a 2000-06-25
Bajando: 2000-06-25 a 2000-07-02
Bajando: 2000-07-02 a 2000-07-09
Bajando: 2000-07-09 a 2000-07-16
Bajando: 2000-07-16 a 2000-07-23
Bajando: 2000-07-23 a 2000-07-30
Bajando: 2000-07-30 a 2000-08-06
Bajando: 2000-08-06 a 2000-08-13
Bajando: 2000-08-13 a 2000-08-20
Bajando: 2000-08-20 a 2000-08-27
Bajando: 2000-08-27 a 2000-09-03
Bajando: 2000-09-03 a 2000-09-10
Bajando: 2000-09-10 a 2000-09-17
Bajando: 2000-09-17 a 2000-09-24
Bajando: 2000-09-24 a 2000-10-01
Bajando: 2000-10-01 a 2000-10-08
Bajando: 2000-10-08 a 2000-10-15
Bajando: 2000-10-15 a 2000-10-22
Bajando: 2000-10-22 a 2000-10-29
Bajando: 2000-10-29 a 2000-11-05
Bajando: 2000-11-05 a 2000-11-12
Bajando: 2000-11-12 a 2000-11-19
Bajando: 2000-11-19 a 2000-11-26
Bajando: 2000-11-26 a 2000-12-03
Bajando: 2000-12-03 a 2000-12-10
Bajando: 2000-12-10 a 2000-12-17
Bajando: 2000-12-17 a 2000-12-24
Bajando: 2000-12-24 a 2000-12-31
Bajando: 2000-12-31 a 2001-01-07
Bajando: 2001-01-07 a 2001-01-14
Bajando: 2001-01-14 a 2001-01-21
Bajando: 2001-01-21 a 2001-01-28
Bajando: 2001-01-28 a 2001-02-04
Bajando: 2001-02-04 a 2001-02-11
Bajando: 2001-02-11 a 2001-02-18
Bajando: 2001-02-18 a 2001-02-25
Bajando: 2001-02-25 a 2001-03-04
Bajando: 2001-03-04 a 2001-03-11
Bajando: 2001-03-11 a 2001-03-18
Bajando: 2001-03-18 a 2001-03-25
Bajando: 2001-03-25 a 2001-04-01
Bajando: 2001-04-01 a 2001-04-08
Bajando: 2001-04-08 a 2001-04-15
Bajando: 2001-04-15 a 2001-04-22
Bajando: 2001-04-22 a 2001-04-29
Bajando: 2001-04-29 a 2001-05-06
Bajando: 2001-05-06 a 2001-05-13
Bajando: 2001-05-13 a 2001-05-20
Bajando: 2001-05-20 a 2001-05-27
Bajando: 2001-05-27 a 2001-06-03
Bajando: 2001-06-03 a 2001-06-10
Bajando: 2001-06-10 a 2001-06-17
Bajando: 2001-06-17 a 2001-06-24
Bajando: 2001-06-24 a 2001-07-01
Bajando: 2001-07-01 a 2001-07-08
Bajando: 2001-07-08 a 2001-07-15
Bajando: 2001-07-15 a 2001-07-22
Bajando: 2001-07-22 a 2001-07-29
Bajando: 2001-07-29 a 2001-08-05
Bajando: 2001-08-05 a 2001-08-12
Bajando: 2001-08-12 a 2001-08-19
Bajando: 2001-08-19 a 2001-08-26
Bajando: 2001-08-26 a 2001-09-02
Bajando: 2001-09-02 a 2001-09-09
Bajando: 2001-09-09 a 2001-09-16
Bajando: 2001-09-16 a 2001-09-23
Bajando: 2001-09-23 a 2001-09-30
Bajando: 2001-09-30 a 2001-10-07
Bajando: 2001-10-07 a 2001-10-14
Bajando: 2001-10-14 a 2001-10-21
Bajando: 2001-10-21 a 2001-10-28
Bajando: 2001-10-28 a 2001-11-04
Bajando: 2001-11-04 a 2001-11-11
Bajando: 2001-11-11 a 2001-11-18
Bajando: 2001-11-18 a 2001-11-25
Bajando: 2001-11-25 a 2001-12-02
Bajando: 2001-12-02 a 2001-12-09
Bajando: 2001-12-09 a 2001-12-16
Bajando: 2001-12-16 a 2001-12-23
Bajando: 2001-12-23 a 2001-12-30
Bajando: 2001-12-30 a 2002-01-06
Bajando: 2002-01-06 a 2002-01-13
Bajando: 2002-01-13 a 2002-01-20
Bajando: 2002-01-20 a 2002-01-27
Bajando: 2002-01-27 a 2002-02-03
Bajando: 2002-02-03 a 2002-02-10
Bajando: 2002-02-10 a 2002-02-17
Bajando: 2002-02-17 a 2002-02-24
Bajando: 2002-02-24 a 2002-03-03
Bajando: 2002-03-03 a 2002-03-10
Bajando: 2002-03-10 a 2002-03-17
Bajando: 2002-03-17 a 2002-03-24
Bajando: 2002-03-24 a 2002-03-31
Bajando: 2002-03-31 a 2002-04-07
Bajando: 2002-04-07 a 2002-04-14
Bajando: 2002-04-14 a 2002-04-21
Bajando: 2002-04-21 a 2002-04-28
Bajando: 2002-04-28 a 2002-05-05
Bajando: 2002-05-05 a 2002-05-12
Bajando: 2002-05-12 a 2002-05-19
Bajando: 2002-05-19 a 2002-05-26
Bajando: 2002-05-26 a 2002-06-02
Bajando: 2002-06-02 a 2002-06-09
Bajando: 2002-06-09 a 2002-06-16
Bajando: 2002-06-16 a 2002-06-23
Bajando: 2002-06-23 a 2002-06-30
Bajando: 2002-06-30 a 2002-07-07
Bajando: 2002-07-07 a 2002-07-14
Bajando: 2002-07-14 a 2002-07-21
Bajando: 2002-07-21 a 2002-07-28
Bajando: 2002-07-28 a 2002-08-04
Bajando: 2002-08-04 a 2002-08-11
Bajando: 2002-08-11 a 2002-08-18
Bajando: 2002-08-18 a 2002-08-25
Bajando: 2002-08-25 a 2002-09-01
Bajando: 2002-09-01 a 2002-09-08
Bajando: 2002-09-08 a 2002-09-15
Bajando: 2002-09-15 a 2002-09-22
Bajando: 2002-09-22 a 2002-09-29
Bajando: 2002-09-29 a 2002-10-06
Bajando: 2002-10-06 a 2002-10-13
Bajando: 2002-10-13 a 2002-10-20
Bajando: 2002-10-20 a 2002-10-27
Bajando: 2002-10-27 a 2002-11-03
Bajando: 2002-11-03 a 2002-11-10
Bajando: 2002-11-10 a 2002-11-17
Bajando: 2002-11-17 a 2002-11-24
Bajando: 2002-11-24 a 2002-12-01
Bajando: 2002-12-01 a 2002-12-08
Bajando: 2002-12-08 a 2002-12-15
Bajando: 2002-12-15 a 2002-12-22
Bajando: 2002-12-22 a 2002-12-29
Bajando: 2002-12-29 a 2003-01-05
Bajando: 2003-01-05 a 2003-01-12
Bajando: 2003-01-12 a 2003-01-19
Bajando: 2003-01-19 a 2003-01-26
Bajando: 2003-01-26 a 2003-02-02
Bajando: 2003-02-02 a 2003-02-09
Bajando: 2003-02-09 a 2003-02-16
Bajando: 2003-02-16 a 2003-02-23
Bajando: 2003-02-23 a 2003-03-02
Bajando: 2003-03-02 a 2003-03-09
Bajando: 2003-03-09 a 2003-03-16
Bajando: 2003-03-16 a 2003-03-23
Bajando: 2003-03-23 a 2003-03-30
Bajando: 2003-03-30 a 2003-04-06
Bajando: 2003-04-06 a 2003-04-13
Bajando: 2003-04-13 a 2003-04-20
Bajando: 2003-04-20 a 2003-04-27
Bajando: 2003-04-27 a 2003-05-04
Bajando: 2003-05-04 a 2003-05-11
Bajando: 2003-05-11 a 2003-05-18
Bajando: 2003-05-18 a 2003-05-25
Bajando: 2003-05-25 a 2003-06-01
Bajando: 2003-06-01 a 2003-06-08
Bajando: 2003-06-08 a 2003-06-15
Bajando: 2003-06-15 a 2003-06-22
Bajando: 2003-06-22 a 2003-06-29
Bajando: 2003-06-29 a 2003-07-06
Bajando: 2003-07-06 a 2003-07-13
Bajando: 2003-07-13 a 2003-07-20
Bajando: 2003-07-20 a 2003-07-27
Bajando: 2003-07-27 a 2003-08-03
Bajando: 2003-08-03 a 2003-08-10
Bajando: 2003-08-10 a 2003-08-17
Bajando: 2003-08-17 a 2003-08-24
Bajando: 2003-08-24 a 2003-08-31
Bajando: 2003-08-31 a 2003-09-07
Bajando: 2003-09-07 a 2003-09-14
Bajando: 2003-09-14 a 2003-09-21
Bajando: 2003-09-21 a 2003-09-28
Bajando: 2003-09-28 a 2003-10-05
Bajando: 2003-10-05 a 2003-10-12
Bajando: 2003-10-12 a 2003-10-19
Bajando: 2003-10-19 a 2003-10-26
Bajando: 2003-10-26 a 2003-11-02
Bajando: 2003-11-02 a 2003-11-09
Bajando: 2003-11-09 a 2003-11-16
Bajando: 2003-11-16 a 2003-11-23
Bajando: 2003-11-23 a 2003-11-30
Bajando: 2003-11-30 a 2003-12-07
Bajando: 2003-12-07 a 2003-12-14
Bajando: 2003-12-14 a 2003-12-21
Bajando: 2003-12-21 a 2003-12-28
Bajando: 2003-12-28 a 2004-01-04
Bajando: 2004-01-04 a 2004-01-11
Bajando: 2004-01-11 a 2004-01-18
Bajando: 2004-01-18 a 2004-01-25
Bajando: 2004-01-25 a 2004-02-01
Bajando: 2004-02-01 a 2004-02-08
Bajando: 2004-02-08 a 2004-02-15
Bajando: 2004-02-15 a 2004-02-22
Bajando: 2004-02-22 a 2004-02-29
Bajando: 2004-02-29 a 2004-03-07
Bajando: 2004-03-07 a 2004-03-14
Bajando: 2004-03-14 a 2004-03-21
Bajando: 2004-03-21 a 2004-03-28
Bajando: 2004-03-28 a 2004-04-04
Bajando: 2004-04-04 a 2004-04-11
Bajando: 2004-04-11 a 2004-04-18
Bajando: 2004-04-18 a 2004-04-25
Bajando: 2004-04-25 a 2004-05-02
Bajando: 2004-05-02 a 2004-05-09
Bajando: 2004-05-09 a 2004-05-16
Bajando: 2004-05-16 a 2004-05-23
Bajando: 2004-05-23 a 2004-05-30
Bajando: 2004-05-30 a 2004-06-06
Bajando: 2004-06-06 a 2004-06-13
Bajando: 2004-06-13 a 2004-06-20
Bajando: 2004-06-20 a 2004-06-27
Bajando: 2004-06-27 a 2004-07-04
Bajando: 2004-07-04 a 2004-07-11
Bajando: 2004-07-11 a 2004-07-18
Bajando: 2004-07-18 a 2004-07-25
Bajando: 2004-07-25 a 2004-08-01
Bajando: 2004-08-01 a 2004-08-08
Bajando: 2004-08-08 a 2004-08-15
Bajando: 2004-08-15 a 2004-08-22
Bajando: 2004-08-22 a 2004-08-29
Bajando: 2004-08-29 a 2004-09-05
Bajando: 2004-09-05 a 2004-09-12
Bajando: 2004-09-12 a 2004-09-19
Bajando: 2004-09-19 a 2004-09-26
Bajando: 2004-09-26 a 2004-10-03
Bajando: 2004-10-03 a 2004-10-10
Bajando: 2004-10-10 a 2004-10-17
Bajando: 2004-10-17 a 2004-10-24
Bajando: 2004-10-24 a 2004-10-31
Bajando: 2004-10-31 a 2004-11-07
Bajando: 2004-11-07 a 2004-11-14
Bajando: 2004-11-14 a 2004-11-21
Bajando: 2004-11-21 a 2004-11-28
Bajando: 2004-11-28 a 2004-12-05
Bajando: 2004-12-05 a 2004-12-12
Bajando: 2004-12-12 a 2004-12-19
Bajando: 2004-12-19 a 2004-12-26
Bajando: 2004-12-26 a 2005-01-02
Bajando: 2005-01-02 a 2005-01-09
Bajando: 2005-01-09 a 2005-01-16
Bajando: 2005-01-16 a 2005-01-23
Bajando: 2005-01-23 a 2005-01-30
Bajando: 2005-01-30 a 2005-02-06
Bajando: 2005-02-06 a 2005-02-13
Bajando: 2005-02-13 a 2005-02-20
Bajando: 2005-02-20 a 2005-02-27
Bajando: 2005-02-27 a 2005-03-06
Bajando: 2005-03-06 a 2005-03-13
Bajando: 2005-03-13 a 2005-03-20
Bajando: 2005-03-20 a 2005-03-27
Bajando: 2005-03-27 a 2005-04-03
Bajando: 2005-04-03 a 2005-04-10
Bajando: 2005-04-10 a 2005-04-17
Bajando: 2005-04-17 a 2005-04-24
Bajando: 2005-04-24 a 2005-05-01
Bajando: 2005-05-01 a 2005-05-08
Bajando: 2005-05-08 a 2005-05-15
Bajando: 2005-05-15 a 2005-05-22
Bajando: 2005-05-22 a 2005-05-29
Bajando: 2005-05-29 a 2005-06-05
Bajando: 2005-06-05 a 2005-06-12
Bajando: 2005-06-12 a 2005-06-19
Bajando: 2005-06-19 a 2005-06-26
Bajando: 2005-06-26 a 2005-07-03
Bajando: 2005-07-03 a 2005-07-10
Bajando: 2005-07-10 a 2005-07-17
Bajando: 2005-07-17 a 2005-07-24
Bajando: 2005-07-24 a 2005-07-31
Bajando: 2005-07-31 a 2005-08-07
Bajando: 2005-08-07 a 2005-08-14
Bajando: 2005-08-14 a 2005-08-21
Bajando: 2005-08-21 a 2005-08-28
Bajando: 2005-08-28 a 2005-09-04
Bajando: 2005-09-04 a 2005-09-11
Bajando: 2005-09-11 a 2005-09-18
Bajando: 2005-09-18 a 2005-09-25
Bajando: 2005-09-25 a 2005-10-02
Bajando: 2005-10-02 a 2005-10-09
Bajando: 2005-10-09 a 2005-10-16
Bajando: 2005-10-16 a 2005-10-23
Bajando: 2005-10-23 a 2005-10-30
Bajando: 2005-10-30 a 2005-11-06
Bajando: 2005-11-06 a 2005-11-13
Bajando: 2005-11-13 a 2005-11-20
Bajando: 2005-11-20 a 2005-11-27
Bajando: 2005-11-27 a 2005-12-04
Bajando: 2005-12-04 a 2005-12-11
Bajando: 2005-12-11 a 2005-12-18
Bajando: 2005-12-18 a 2005-12-25
Bajando: 2005-12-25 a 2006-01-01
Bajando: 2006-01-01 a 2006-01-08
Bajando: 2006-01-08 a 2006-01-15
Bajando: 2006-01-15 a 2006-01-22
Bajando: 2006-01-22 a 2006-01-29
Bajando: 2006-01-29 a 2006-02-05
Bajando: 2006-02-05 a 2006-02-12
Bajando: 2006-02-12 a 2006-02-19
Bajando: 2006-02-19 a 2006-02-26
Bajando: 2006-02-26 a 2006-03-05
Bajando: 2006-03-05 a 2006-03-12
Bajando: 2006-03-12 a 2006-03-19
Bajando: 2006-03-19 a 2006-03-26
Bajando: 2006-03-26 a 2006-04-02
Bajando: 2006-04-02 a 2006-04-09
Bajando: 2006-04-09 a 2006-04-16
Bajando: 2006-04-16 a 2006-04-23
Bajando: 2006-04-23 a 2006-04-30
Bajando: 2006-04-30 a 2006-05-07
Bajando: 2006-05-07 a 2006-05-14
Bajando: 2006-05-14 a 2006-05-21
Bajando: 2006-05-21 a 2006-05-28
Bajando: 2006-05-28 a 2006-06-04
Bajando: 2006-06-04 a 2006-06-11
Bajando: 2006-06-11 a 2006-06-18
Bajando: 2006-06-18 a 2006-06-25
Bajando: 2006-06-25 a 2006-07-02
Bajando: 2006-07-02 a 2006-07-09
Bajando: 2006-07-09 a 2006-07-16
Bajando: 2006-07-16 a 2006-07-23
Bajando: 2006-07-23 a 2006-07-30
Bajando: 2006-07-30 a 2006-08-06
Bajando: 2006-08-06 a 2006-08-13

In [15]:
start = datetime(1995, 1, 1)
end = datetime(2025, 1, 1)

all_asteroids_raw = {}
current = start

while current < end:
    week_end = current + timedelta(days=7)
    start_str = current.strftime("%Y-%m-%d")
    end_str = week_end.strftime("%Y-%m-%d")
    
    neos_week = fetch_neos(start_str, end_str, NASA_API_KEY)
    all_asteroids_raw.update(neos_week)
    
    current = week_end
    time.sleep(0.5)

print(f"Total de días bajados: {len(all_asteroids_raw)}")

KeyboardInterrupt:

In [ ]:
import json

with open("../data/raw/neo_raw.json", "w") as f:
    json.dump(all_asteroids_raw, f)

print("Datos guardados correctamente")

In [ ]:
import os
size_mb = os.path.getsize("../data/raw/neo_raw.json") / (1024 * 1024)
print(f"Tamaño del archivo: {size_mb:.2f} MB")

In [ ]:
all_asteroids = []

for date, neo_list in all_asteroids_raw.items():
    for neo in neo_list:
        asteroid = {
            "id": neo["id"],
            "name": neo["name"],
            "is_potentially_hazardous": neo["is_potentially_hazardous_asteroid"],
            "diameter_km_min": neo["estimated_diameter"]["kilometers"]["estimated_diameter_min"],
            "diameter_km_max": neo["estimated_diameter"]["kilometers"]["estimated_diameter_max"],
            "close_approach_date": neo["close_approach_data"][0]["close_approach_date"],
            "miss_distance_km": neo["close_approach_data"][0]["miss_distance"]["kilometers"],
            "velocity_kmh": neo["close_approach_data"][0]["relative_velocity"]["kilometers_per_hour"]
        }
        all_asteroids.append(asteroid)

df = pd.DataFrame(all_asteroids)
print(df.shape)

In [ ]:
df["miss_distance_km"] = pd.to_numeric(df["miss_distance_km"])
df["velocity_kmh"] = pd.to_numeric(df["velocity_kmh"])
df["close_approach_date"] = pd.to_datetime(df["close_approach_date"])

print(df.dtypes)
print(df.isnull().sum())

In [ ]:
df.to_csv("../data/processed/neo_clean.csv", index=False)
print("Guardado correctamente")

In [20]:
df = pd.read_csv("../data/processed/neo_clean.csv")
print(df.shape)
df.head()

(79439, 8)

,id,name,is_potentially_hazardous,diameter_km_min,diameter_km_max,close_approach_date,miss_distance_km,velocity_kmh
0,3516633,(2010 HA),False,0.044112,0.098637,1995-01-07,2.959363e+07,22395.337325
1,3837644,(2019 AY3),False,0.045767,0.102339,1995-01-07,1.909375e+07,80679.829203
2,3843493,(2019 PY),False,0.023150,0.051765,1995-01-07,1.440650e+07,17995.842471
3,2446862,446862 (2001 VB76),True,0.208236,0.465629,1995-01-08,7.622845e+06,27326.492203
4,3765015,(2016 WR48),False,0.160160,0.358129,1995-01-08,4.339162e+07,26721.139515